import React, { useMemo, useState } from "react";
import ReactFlow, { Background, Controls, Handle, Position } from "reactflow";
import "reactflow/dist/style.css";
import { journeys, DISPOSITIONS, srcUrl } from "./journeys.js";

function DocNode({ data }) {
  const color = DISPOSITIONS[data.disposition].color;
  return (
    <div className="doc-node" style={{ borderColor: color }} onClick={data.onClick}>
      <Handle type="target" position={Position.Left} />
      <div className="doc-node__label">{data.label}</div>
      <div className="doc-node__cls">{data.cls}</div>
      {data.table && <div className="doc-node__table">{data.table}</div>}
      <Handle type="source" position={Position.Right} />
    </div>
  );
}

const nodeTypes = { doc: DocNode };

export default function App() {
  const [activeId, setActiveId] = useState(journeys[0].id);
  const [selected, setSelected] = useState(null);
  const journey = journeys.find((j) => j.id === activeId);

  const { nodes, edges } = useMemo(() => {
    const idx = Object.fromEntries(journey.nodes.map((n, i) => [n.id, i]));
    const nodes = journey.nodes.map((n, i) => ({
      id: n.id,
      type: "doc",
      position: { x: i * 230, y: 80 + (i % 2) * 70 },
      data: { ...n, disposition: journey.disposition, onClick: () => setSelected(n) },
    }));
    const edges = journey.edges.map(([s, t]) => ({
      id: `${s}-${t}`,
      source: s,
      target: t,
      animated: true,
      style: { stroke: "#94a3b8" },
    }));
    return { nodes, edges, idx };
  }, [journey]);

  return (
    <div className="app">
      <header className="app__header">
        <h1>iDempiere — User Journey Migration Map</h1>
        <p className="app__sub">
          Legacy Oracle/COTS ERP · journeys rediscovered from code · color = migration disposition
        </p>
      </header>

      <div className="legend">
        {Object.entries(DISPOSITIONS).map(([k, v]) => (
          <span key={k} className="legend__item">
            <i style={{ background: v.color }} /> {v.label}
            <small>— {v.hint}</small>
          </span>
        ))}
      </div>

      <div className="tabs">
        {journeys.map((j) => (
          <button
            key={j.id}
            className={"tab" + (j.id === activeId ? " tab--active" : "")}
            style={{ borderBottomColor: j.id === activeId ? DISPOSITIONS[j.disposition].color : "transparent" }}
            onClick={() => { setActiveId(j.id); setSelected(null); }}
          >
            <span className="tab__dot" style={{ background: DISPOSITIONS[j.disposition].color }} />
            {j.name}
          </button>
        ))}
      </div>

      <div className="body">
        <div className="canvas">
          <ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView proOptions={{ hideAttribution: true }}>
            <Background />
            <Controls showInteractive={false} />
          </ReactFlow>
        </div>

        <aside className="panel">
          <div className="panel__badge" style={{ background: DISPOSITIONS[journey.disposition].color }}>
            {DISPOSITIONS[journey.disposition].label}
          </div>
          <h2>{journey.name}</h2>
          <p className="panel__summary">{journey.summary}</p>

          <h3>Decision drivers</h3>
          <table className="metrics">
            <tbody>
              <tr><td>Oracle coupling</td><td>{journey.metrics.oracleCoupling}</td></tr>
              <tr><td>Complexity</td><td>{journey.metrics.complexity}</td></tr>
              <tr><td>Data volume</td><td>{journey.metrics.dataVolume}</td></tr>
              <tr><td>Blast radius</td><td>{journey.metrics.blastRadius}</td></tr>
            </tbody>
          </table>

          <h3>Rationale</h3>
          <p className="panel__rationale">{journey.rationale}</p>

          {selected ? (
            <div className="node-detail">
              <h3>{selected.label} — <code>{selected.cls}</code></h3>
              <ul>
                {selected.table && <li>Tables: <code>{selected.table}</code></li>}
                {selected.lines && <li>Source size: {selected.lines} lines</li>}
                {selected.oracle && <li className="oracle">Oracle coupling: {selected.oracle}</li>}
              </ul>
              <a className="src-link" href={srcUrl(selected.file, selected.lines && 1)} target="_blank" rel="noreferrer">
                View source ↗
              </a>
            </div>
          ) : (
            <p className="hint">Click a document node to inspect its class, tables and source.</p>
          )}
        </aside>
      </div>

      <footer className="app__footer">
        Generated by Devin from the iDempiere codebase · stand-in for a legacy Oracle/COTS ERP
      </footer>
    </div>
  );
}
